<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2018/9/25
 * Time: 16:12
 */
namespace app\admin\controller;

use think\Controller;

class Common extends Controller {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->weburl = 'mp.jianghairui.com';
        if(!$this->needSession()) {
            $this->error('请登录后操作',url('Login/index'));
        }
    }

    public function needSession() {
        $noNeedSession = [
            'Login/index',
            'Login/vcode',
            'Login/login',
            'Login/test',
        ];
        if (in_array(request()->controller() . '/' . request()->action(), $noNeedSession)) {
            return true;
        }else {
            if(session('username') && session('mploginstatus') && session('mploginstatus') == md5(session('username') . 'jiang')) {
                return true;
            }else {
                return false;
            }
        }
    }



}