<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2018/9/18
 * Time: 21:36
 */
namespace app\index\controller;
use think\Controller;
class Common extends Controller {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->openid = 'openid';
        $this->mp_config = [
            'app_id' => 'wxc838d57e376ce663',
            'secret' => '8245fa83deb50600034d87237b628764',

            // 下面为可选项
            // 指定 API 调用返回结果的类型：array(default)/collection/object/raw/自定义类名
            'response_type' => 'array',

            'log' => [
                'level' => 'debug',
                'file' => ROOT_PATH . '/wechat.log',
            ],
        ];
    }


}