<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2018/9/18
 * Time: 21:36
 */
namespace app\index\controller;
use think\Controller;
use think\exception\HttpResponseException;
class Common extends Controller {

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->myinfo = '';
        $this->mp_config = [
            'app_id' => 'wx0d6f8a78265b1229',
            'secret' => 'b7cfdce371e0c100e7fc1d482933d7f5',

            // 下面为可选项
            // 指定 API 调用返回结果的类型：array(default)/collection/object/raw/自定义类名
            'response_type' => 'array',
            'log' => [
                'level' => 'debug',
                'file' => ROOT_PATH . '/wechat.log',
            ],
        ];
        $this->checkSession();
    }

    private function checkSession() {
        $noneed = [
            'Login/login',
        ];
        if (in_array(request()->controller() . '/' . request()->action(), $noneed)) {
            return true;
        }else {
            if(input('post.token') && mredis()->get(input('post.token'))) {
                $this->myinfo = mredis()->get(input('post.token'));
                return true;
            }else {
                throw new HttpResponseException(ajax('invalid token',3));
            }
        }

    }

    protected function checkPost($postArray) {
        if(empty($postArray)) {
            throw new HttpResponseException(ajax($postArray,-2));
        }
        foreach ($postArray as $value) {
            if (empty($value)) {
                throw new HttpResponseException(ajax($postArray,-2));
            }
        }
        return true;
    }


}